### ISSUE TITLE
Pull the forms provider into this?

### ISSUE THREAD

**Issue by lars-erik** [umbraco/Umbraco.Courier.Contrib#13]

**Comment by leekelleher** [comment]
I think consolidating the repositories would be a good idea.

I believe that the Forms provider itself has an assembly dependency on UmbracoForms, so wouldn't be part of the "Umbraco.Courier.Contrib.Resolvers" project/DLL, (as @sitereactor outlines in https://github.com/umbraco/Umbraco.Courier.Contrib/issues/19#issuecomment-277954402).

I'm not sure who "owns" the Forms provider repository these days? _It's been a while since the last commit._

**Comment by nul800sebastiaan** [comment]
Sorry for the (very) late reply 🙈

If there's still demand for adding the Forms provider I'll look into it. I am not sure how much we can do as it is quite tightly coupled to Forms itself so might be difficult to separate it out. I'll close for now but let me know if there's a real demand for this still.

**Comment by lars-erik** [comment]
LOL!

Courier Schworier, Deploy Swemploy, V8 Swheight…
Let's go about our business and pray the powers that be someday grant us the utopian society where software aren't rushed out the door to satisfy the masses.

RIP issue.
