### ISSUE TITLE
Umbraco courier installation breaking when working with LDAP active directory logins 

### ISSUE THREAD

**Issue by pyajamanam** [umbraco/Umbraco.Courier.Contrib#44]
Hi Nathan,
I am using workflow installed in umbraco 7.9.2 version, i am using active directory logins.when i login backoffice with active directory and install package showing below error.
please suggest me if am missing anything when installing plumber.
![plumberissue](https://user-images.githubusercontent.com/33079424/44336053-ceb64680-a493-11e8-9881-9c82cece3249.PNG)

**Comment by clausjensen** [comment]
Hi @pyajamanam 

I'm not really sure why you've opened this issue on the Courier.Contrib tracker. It doesn't really have anything to do with Courier or any of the data resolvers in this repository.

Also .. Nathan will most likely never see this issue report, since this repository is in no way connected to his Plumber project.

I'd suggest you create an issue on his project instead: https://github.com/nathanwoulfe/Plumber

Best regards,
Claus

**Comment by pyajamanam** [comment]
Claus,
its by mistake happened,I have created the issue in Nathan repository,good to close this issue.
